
version: '3.1'

services:
  db:
    image: mysql:5.6
    container_name: db-service
    # DB型別為utf8mb4 ...
    command: ['--character-set-server=utf8', '--collation-server=utf8_unicode_ci', --default-authentication-plugin=mysql_native_password]
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: qwe1234
      MYSQL_DATABASE: Test

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8888:8080